/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-08-11 05:39:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" data-theme=\"dark\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login — Online Examination System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/glassmorphism.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("        .login-card {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 440px;\n");
      out.write("        }\n");
      out.write("        .login-logo {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("        .login-logo h1 {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            color: #3b82f6;\n");
      out.write("        }\n");
      out.write("        .theme-toggle-container {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 20px;\n");
      out.write("            right: 20px;\n");
      out.write("        }\n");
      out.write("        .theme-toggle-btn {\n");
      out.write("            background: var(--glass-bg);\n");
      out.write("            border: 1px solid var(--glass-border);\n");
      out.write("            border-radius: 50%;\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("        .theme-toggle-btn:hover {\n");
      out.write("            background: var(--glass-bg-strong);\n");
      out.write("            transform: scale(1.1);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        // Theme management\n");
      out.write("        (function() {\n");
      out.write("            const savedTheme = localStorage.getItem('theme') || 'dark';\n");
      out.write("            document.documentElement.setAttribute('data-theme', savedTheme);\n");
      out.write("        })();\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"theme-toggle-container\">\n");
      out.write("        <button id=\"theme-toggle\" class=\"theme-toggle-btn\" title=\"Toggle Theme\">🌙</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"glass-panel glass-panel--strong login-card page-enter\">\n");
      out.write("        <div class=\"login-logo\">\n");
      out.write("            <h1>🎓 Stark Exam Portal</h1>\n");
      out.write("            <p>Online Examination & Student Management System</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            String error = request.getParameter("error");
            String msg = request.getParameter("msg");
            if (error != null) {
        
      out.write("\n");
      out.write("            <div style=\"background: rgba(248, 113, 113, 0.2); border: 1px solid var(--danger); padding: 12px; border-radius: 10px; margin-bottom: 16px; color: #f87171; text-align: center; font-size: 0.9rem;\">\n");
      out.write("                ");
 if ("invalid_credentials".equals(error)) { 
      out.write("\n");
      out.write("                    ❌ Invalid username or password. Please try again.\n");
      out.write("                ");
 } else if ("please_login".equals(error)) { 
      out.write("\n");
      out.write("                    ⚠️ Please log in to access the system.\n");
      out.write("                ");
 } else if ("unauthorized".equals(error)) { 
      out.write("\n");
      out.write("                    🚫 Access Denied: You do not have permission for that area.\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    An error occurred. Please try again.\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        ");
 if (msg != null && "logged_out".equals(msg)) { 
      out.write("\n");
      out.write("            <div style=\"background: rgba(52, 211, 153, 0.2); border: 1px solid var(--success); padding: 12px; border-radius: 10px; margin-bottom: 16px; color: #34d399; text-align: center; font-size: 0.9rem;\">\n");
      out.write("                ✅ You have been logged out successfully.\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"post\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"username\">Username / ERP ID</label>\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" placeholder=\"Enter your username\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"password\">Password</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Enter your password\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn btn--primary\" style=\"width: 100%; padding: 12px; font-size: 1rem; margin-top: 8px;\">\n");
      out.write("                Sign In →\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // Theme toggle functionality for login page\n");
      out.write("        document.getElementById('theme-toggle').addEventListener('click', function() {\n");
      out.write("            const html = document.documentElement;\n");
      out.write("            const currentTheme = html.getAttribute('data-theme');\n");
      out.write("            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';\n");
      out.write("            \n");
      out.write("            html.setAttribute('data-theme', newTheme);\n");
      out.write("            localStorage.setItem('theme', newTheme);\n");
      out.write("            \n");
      out.write("            // Update button icon\n");
      out.write("            this.textContent = newTheme === 'dark' ? '🌙' : '☀️';\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Set initial button icon based on current theme\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            const currentTheme = document.documentElement.getAttribute('data-theme');\n");
      out.write("            const themeToggle = document.getElementById('theme-toggle');\n");
      out.write("            if (themeToggle) {\n");
      out.write("                themeToggle.textContent = currentTheme === 'dark' ? '🌙' : '☀️';\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
